def open_file(title: str, initialdir: str, filters: list[str] | None = ...) -> str | None: ...
def open_multiple(title: str, initialdir: str, filters: list[str] | None = ...) -> list[str]: ...
def save_file(title: str, initialdir: str, filters: list[str] | None = ..., default_name: str | None = ...) -> str | None: ...
def open_directory(title: str, initialdir: str) -> str | None: ...
