def open_file(title: str, initialdir: str, filters: str = ...) -> str | None: ...
def open_multiple(title: str, initialdir: str, filters: str = ...) -> list[str]: ...
def save_file(title: str, initialdir: str, filters: str = ..., default_name: str = ...) -> str | None: ...
def open_directory(title: str, initialdir: str) -> str | None: ...
