from collections.abc import Callable

def open_file(title: str, initialdir: str, filters: str = ..., event_pump: Callable[[], bool | None] | None = ...) -> str | None: ...
def open_multiple(title: str, initialdir: str, filters: str = ..., event_pump: Callable[[], bool | None] | None = ...) -> list[str]: ...
def save_file(title: str, initialdir: str, filters: str = ..., default_name: str = ..., event_pump: Callable[[], bool | None] | None = ...) -> str | None: ...
def open_directory(title: str, initialdir: str, event_pump: Callable[[], bool | None] | None = ...) -> str | None: ...
